name = "core-concepts-in-hindu-philoso"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "src/index.js"

[build]
command = "npm run build"

[env.production]
name = "core-concepts-in-hindu-philoso"
route = ""
zone_id = ""

[assets]
directory = "./_site"
