name = "core-concepts-in-hindu-philoso"
type = "javascript"
main = ""
compatibility_date = "2024-01-01"

[env.production]
name = "core-concepts-in-hindu-philoso"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "service-worker"

[[routes]]
pattern = "*"
zone_name = ""

[assets]
directory = "./_site"
