name = "core-concepts-in-hindu-philoso"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "src/index.js"
site = { bucket = "./_site" }

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
